language: node_js
node_js:
- '0.10'
script: make test-ci
install:
- npm install
- npm install bower -g
- bower install
addons:
  sauce_connect: true
env:
  global:
  - secure: j/heHAmwzfjojIuk3Vl0fc/5AVizEsYhoxbAYoDOR/eHwtIHRFgAtxeJxglwL5QM28sjBgZ9Z1Mk34SjIwhn96AFYQjD1ufZxAy6u+Zrp/Tk2ZYbtQxPV9XwaMr/c6AULRELO0xKMn01o48nTdra67Do/8KscVk1e5pC6BJ298A=
  - secure: coQFTKFapwC60YquGpRE/XcFzCVVPhDYKJYRIS/Ygbe+Ukqe+WXNm34hwjEr4ZCf7PkKxb1GiJ2iCf9m06i8KJTfn4qCXbmLLOxlubvXa2bpwNNdQwgB6pBU6wbFgWjfXwKqurjt0yCwdOo8SVaB5ozdMvn2GmlG0e/RBXUp9cA=
