language: node_js
sudo: false
node_js: stable
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install
script:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then gulp ci; else gulp pr; fi
env:
  global:
    - secure: khV7nMQEHsPUMAo2iUh42pUc/aktwlc+QpE/B4BHSh2fCjbtfPHdfYMNpgJwbil9JPhKtJs7h+5kPRVcy55MHrCc1JURLU31vcORSo/kxZMfSUGFYWp0eFcS3ekwxYkpBNKSQ6vMzTxxIQF3ZJzT+m3aG+1NPeQ2+6iycG0xiJs=
    - secure: ROtWLhHTPOg7bUSgysdlo2Tl0PugWnSn7eEU3lgaZxgath2Wqq3295LpR5iFwpIL/bVqm+FSIeYZ/vyTm1UJ8ORjawSJvj66X8oixfd0SNISvTmieJI4rwsFdVocnF6Bc99WO8uD50FNOL7oUfyquhlTpuGVYIbLgBmgFTEY/5g=
